//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class automation_systemEntities : DbContext
    {
        public automation_systemEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vw_Users> Vw_Users { get; set; }
        public virtual DbSet<Remember> Remembers { get; set; }
        public virtual DbSet<Vw_Remember> Vw_Remember { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<Vw_UserLog> Vw_UserLog { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Vw_jobs> Vw_jobs { get; set; }
        public virtual DbSet<Userjob> Userjobs { get; set; }
        public virtual DbSet<Vw_UserJobs> Vw_UserJobs { get; set; }
        public virtual DbSet<bimehShodeh> bimehShodehs { get; set; }
        public virtual DbSet<Vw_BimehShodeh> Vw_BimehShodeh { get; set; }
        public virtual DbSet<Vw_bimehShodeh3> Vw_bimehShodeh3 { get; set; }
        public virtual DbSet<SentLetter> SentLetters { get; set; }
        public virtual DbSet<AttachFile> AttachFiles { get; set; }
        public virtual DbSet<Letter> Letters { get; set; }
        public virtual DbSet<Vw_Letters> Vw_Letters { get; set; }
        public virtual DbSet<Vw_recieveLetters> Vw_recieveLetters { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<SentNote> SentNotes { get; set; }
        public virtual DbSet<Vw_Notes> Vw_Notes { get; set; }
        public virtual DbSet<Vw_recieveNotes> Vw_recieveNotes { get; set; }
        public virtual DbSet<Vw_SentNote> Vw_SentNote { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<Vw_news> Vw_news { get; set; }
        public virtual DbSet<ReferenceLetter> ReferenceLetters { get; set; }
        public virtual DbSet<Vw_recieveReference> Vw_recieveReference { get; set; }
        public virtual DbSet<Vw_referenceLetter> Vw_referenceLetter { get; set; }
        public virtual DbSet<systemPart> systemParts { get; set; }
        public virtual DbSet<Vw_systemParts> Vw_systemParts { get; set; }
        public virtual DbSet<UsereAccess> UsereAccesses { get; set; }
        public virtual DbSet<work> works { get; set; }
        public virtual DbSet<Vw_works> Vw_works { get; set; }
        public virtual DbSet<Vw_showChartInfo> Vw_showChartInfo { get; set; }
        public virtual DbSet<support> supports { get; set; }
        public virtual DbSet<Vw_supports> Vw_supports { get; set; }
        public virtual DbSet<View_supports> View_supports { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    
        public virtual int Sp_insert_Users(string userFirstName, string userFamily, string username, string password, string personalCode, string email, Nullable<byte> gender, Nullable<byte> activity, string userTel, string birthDayDate, byte[] userImage, string createDate, byte[] signatures)
        {
            var userFirstNameParameter = userFirstName != null ?
                new ObjectParameter("UserFirstName", userFirstName) :
                new ObjectParameter("UserFirstName", typeof(string));
    
            var userFamilyParameter = userFamily != null ?
                new ObjectParameter("UserFamily", userFamily) :
                new ObjectParameter("UserFamily", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var personalCodeParameter = personalCode != null ?
                new ObjectParameter("PersonalCode", personalCode) :
                new ObjectParameter("PersonalCode", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(byte));
    
            var activityParameter = activity.HasValue ?
                new ObjectParameter("Activity", activity) :
                new ObjectParameter("Activity", typeof(byte));
    
            var userTelParameter = userTel != null ?
                new ObjectParameter("UserTel", userTel) :
                new ObjectParameter("UserTel", typeof(string));
    
            var birthDayDateParameter = birthDayDate != null ?
                new ObjectParameter("BirthDayDate", birthDayDate) :
                new ObjectParameter("BirthDayDate", typeof(string));
    
            var userImageParameter = userImage != null ?
                new ObjectParameter("UserImage", userImage) :
                new ObjectParameter("UserImage", typeof(byte[]));
    
            var createDateParameter = createDate != null ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(string));
    
            var signaturesParameter = signatures != null ?
                new ObjectParameter("Signatures", signatures) :
                new ObjectParameter("Signatures", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_insert_Users", userFirstNameParameter, userFamilyParameter, usernameParameter, passwordParameter, personalCodeParameter, emailParameter, genderParameter, activityParameter, userTelParameter, birthDayDateParameter, userImageParameter, createDateParameter, signaturesParameter);
        }
    
        public virtual int Sp_Update_Users(Nullable<int> userId, string userFirstName, string userFamily, string personalCode, string email, Nullable<byte> gender, string userTel, string birthDayDate, byte[] userImage)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var userFirstNameParameter = userFirstName != null ?
                new ObjectParameter("UserFirstName", userFirstName) :
                new ObjectParameter("UserFirstName", typeof(string));
    
            var userFamilyParameter = userFamily != null ?
                new ObjectParameter("UserFamily", userFamily) :
                new ObjectParameter("UserFamily", typeof(string));
    
            var personalCodeParameter = personalCode != null ?
                new ObjectParameter("PersonalCode", personalCode) :
                new ObjectParameter("PersonalCode", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(byte));
    
            var userTelParameter = userTel != null ?
                new ObjectParameter("UserTel", userTel) :
                new ObjectParameter("UserTel", typeof(string));
    
            var birthDayDateParameter = birthDayDate != null ?
                new ObjectParameter("BirthDayDate", birthDayDate) :
                new ObjectParameter("BirthDayDate", typeof(string));
    
            var userImageParameter = userImage != null ?
                new ObjectParameter("UserImage", userImage) :
                new ObjectParameter("UserImage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Users", userIdParameter, userFirstNameParameter, userFamilyParameter, personalCodeParameter, emailParameter, genderParameter, userTelParameter, birthDayDateParameter, userImageParameter);
        }
    
        public virtual int Sp_Update_Users_noImage(Nullable<int> userId, string userFirstName, string userFamily, string personalCode, string email, Nullable<byte> gender, string userTel, string birthDayDate)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var userFirstNameParameter = userFirstName != null ?
                new ObjectParameter("UserFirstName", userFirstName) :
                new ObjectParameter("UserFirstName", typeof(string));
    
            var userFamilyParameter = userFamily != null ?
                new ObjectParameter("UserFamily", userFamily) :
                new ObjectParameter("UserFamily", typeof(string));
    
            var personalCodeParameter = personalCode != null ?
                new ObjectParameter("PersonalCode", personalCode) :
                new ObjectParameter("PersonalCode", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(byte));
    
            var userTelParameter = userTel != null ?
                new ObjectParameter("UserTel", userTel) :
                new ObjectParameter("UserTel", typeof(string));
    
            var birthDayDateParameter = birthDayDate != null ?
                new ObjectParameter("BirthDayDate", birthDayDate) :
                new ObjectParameter("BirthDayDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Users_noImage", userIdParameter, userFirstNameParameter, userFamilyParameter, personalCodeParameter, emailParameter, genderParameter, userTelParameter, birthDayDateParameter);
        }
    
        public virtual int SP_Update_ExitDate(Nullable<int> userId, string exitDateTime)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var exitDateTimeParameter = exitDateTime != null ?
                new ObjectParameter("ExitDateTime", exitDateTime) :
                new ObjectParameter("ExitDateTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_ExitDate", userIdParameter, exitDateTimeParameter);
        }
    
        public virtual ObjectResult<Sp_ShowAllUserInfo_Result> Sp_ShowAllUserInfo(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ShowAllUserInfo_Result>("Sp_ShowAllUserInfo", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Show_AllUserInfo_Result> SP_Show_AllUserInfo(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Show_AllUserInfo_Result>("SP_Show_AllUserInfo", userIdParameter);
        }
    
        public virtual int sp_insert_BimehShodeh(string bFirstName, string bFamily, string bFather, string bbirthCode, string bbirthplc, string bbirthdate, string bregdate, Nullable<int> buserId, Nullable<int> bbimecode, string bJob, string bjobeCode, string bbimehType, Nullable<int> bpersonelCode, string btozih, string bramz, string bnatCode, Nullable<long> bkargahNo, string btel, string bmobile)
        {
            var bFirstNameParameter = bFirstName != null ?
                new ObjectParameter("bFirstName", bFirstName) :
                new ObjectParameter("bFirstName", typeof(string));
    
            var bFamilyParameter = bFamily != null ?
                new ObjectParameter("bFamily", bFamily) :
                new ObjectParameter("bFamily", typeof(string));
    
            var bFatherParameter = bFather != null ?
                new ObjectParameter("bFather", bFather) :
                new ObjectParameter("bFather", typeof(string));
    
            var bbirthCodeParameter = bbirthCode != null ?
                new ObjectParameter("bbirthCode", bbirthCode) :
                new ObjectParameter("bbirthCode", typeof(string));
    
            var bbirthplcParameter = bbirthplc != null ?
                new ObjectParameter("bbirthplc", bbirthplc) :
                new ObjectParameter("bbirthplc", typeof(string));
    
            var bbirthdateParameter = bbirthdate != null ?
                new ObjectParameter("bbirthdate", bbirthdate) :
                new ObjectParameter("bbirthdate", typeof(string));
    
            var bregdateParameter = bregdate != null ?
                new ObjectParameter("bregdate", bregdate) :
                new ObjectParameter("bregdate", typeof(string));
    
            var buserIdParameter = buserId.HasValue ?
                new ObjectParameter("buserId", buserId) :
                new ObjectParameter("buserId", typeof(int));
    
            var bbimecodeParameter = bbimecode.HasValue ?
                new ObjectParameter("bbimecode", bbimecode) :
                new ObjectParameter("bbimecode", typeof(int));
    
            var bJobParameter = bJob != null ?
                new ObjectParameter("bJob", bJob) :
                new ObjectParameter("bJob", typeof(string));
    
            var bjobeCodeParameter = bjobeCode != null ?
                new ObjectParameter("bjobeCode", bjobeCode) :
                new ObjectParameter("bjobeCode", typeof(string));
    
            var bbimehTypeParameter = bbimehType != null ?
                new ObjectParameter("bbimehType", bbimehType) :
                new ObjectParameter("bbimehType", typeof(string));
    
            var bpersonelCodeParameter = bpersonelCode.HasValue ?
                new ObjectParameter("bpersonelCode", bpersonelCode) :
                new ObjectParameter("bpersonelCode", typeof(int));
    
            var btozihParameter = btozih != null ?
                new ObjectParameter("btozih", btozih) :
                new ObjectParameter("btozih", typeof(string));
    
            var bramzParameter = bramz != null ?
                new ObjectParameter("bramz", bramz) :
                new ObjectParameter("bramz", typeof(string));
    
            var bnatCodeParameter = bnatCode != null ?
                new ObjectParameter("bnatCode", bnatCode) :
                new ObjectParameter("bnatCode", typeof(string));
    
            var bkargahNoParameter = bkargahNo.HasValue ?
                new ObjectParameter("bkargahNo", bkargahNo) :
                new ObjectParameter("bkargahNo", typeof(long));
    
            var btelParameter = btel != null ?
                new ObjectParameter("btel", btel) :
                new ObjectParameter("btel", typeof(string));
    
            var bmobileParameter = bmobile != null ?
                new ObjectParameter("bmobile", bmobile) :
                new ObjectParameter("bmobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_BimehShodeh", bFirstNameParameter, bFamilyParameter, bFatherParameter, bbirthCodeParameter, bbirthplcParameter, bbirthdateParameter, bregdateParameter, buserIdParameter, bbimecodeParameter, bJobParameter, bjobeCodeParameter, bbimehTypeParameter, bpersonelCodeParameter, btozihParameter, bramzParameter, bnatCodeParameter, bkargahNoParameter, btelParameter, bmobileParameter);
        }
    
        public virtual int Sp_Update_BimehShodeh(Nullable<int> bID, string bFirstName, string bFamily, string bFather, string bbirthCode, string bbirthplc, string bbirthdate, string bregdate, Nullable<int> buserId, Nullable<int> bbimecode, string bJob, string bjobeCode, string bbimehType, Nullable<int> bpersonelCode, string btozih, string bramz, string bnatCode, Nullable<long> bkargahNo, string btel, string bmobile)
        {
            var bIDParameter = bID.HasValue ?
                new ObjectParameter("BID", bID) :
                new ObjectParameter("BID", typeof(int));
    
            var bFirstNameParameter = bFirstName != null ?
                new ObjectParameter("bFirstName", bFirstName) :
                new ObjectParameter("bFirstName", typeof(string));
    
            var bFamilyParameter = bFamily != null ?
                new ObjectParameter("bFamily", bFamily) :
                new ObjectParameter("bFamily", typeof(string));
    
            var bFatherParameter = bFather != null ?
                new ObjectParameter("bFather", bFather) :
                new ObjectParameter("bFather", typeof(string));
    
            var bbirthCodeParameter = bbirthCode != null ?
                new ObjectParameter("bbirthCode", bbirthCode) :
                new ObjectParameter("bbirthCode", typeof(string));
    
            var bbirthplcParameter = bbirthplc != null ?
                new ObjectParameter("bbirthplc", bbirthplc) :
                new ObjectParameter("bbirthplc", typeof(string));
    
            var bbirthdateParameter = bbirthdate != null ?
                new ObjectParameter("bbirthdate", bbirthdate) :
                new ObjectParameter("bbirthdate", typeof(string));
    
            var bregdateParameter = bregdate != null ?
                new ObjectParameter("bregdate", bregdate) :
                new ObjectParameter("bregdate", typeof(string));
    
            var buserIdParameter = buserId.HasValue ?
                new ObjectParameter("buserId", buserId) :
                new ObjectParameter("buserId", typeof(int));
    
            var bbimecodeParameter = bbimecode.HasValue ?
                new ObjectParameter("bbimecode", bbimecode) :
                new ObjectParameter("bbimecode", typeof(int));
    
            var bJobParameter = bJob != null ?
                new ObjectParameter("bJob", bJob) :
                new ObjectParameter("bJob", typeof(string));
    
            var bjobeCodeParameter = bjobeCode != null ?
                new ObjectParameter("bjobeCode", bjobeCode) :
                new ObjectParameter("bjobeCode", typeof(string));
    
            var bbimehTypeParameter = bbimehType != null ?
                new ObjectParameter("bbimehType", bbimehType) :
                new ObjectParameter("bbimehType", typeof(string));
    
            var bpersonelCodeParameter = bpersonelCode.HasValue ?
                new ObjectParameter("bpersonelCode", bpersonelCode) :
                new ObjectParameter("bpersonelCode", typeof(int));
    
            var btozihParameter = btozih != null ?
                new ObjectParameter("btozih", btozih) :
                new ObjectParameter("btozih", typeof(string));
    
            var bramzParameter = bramz != null ?
                new ObjectParameter("bramz", bramz) :
                new ObjectParameter("bramz", typeof(string));
    
            var bnatCodeParameter = bnatCode != null ?
                new ObjectParameter("bnatCode", bnatCode) :
                new ObjectParameter("bnatCode", typeof(string));
    
            var bkargahNoParameter = bkargahNo.HasValue ?
                new ObjectParameter("bkargahNo", bkargahNo) :
                new ObjectParameter("bkargahNo", typeof(long));
    
            var btelParameter = btel != null ?
                new ObjectParameter("btel", btel) :
                new ObjectParameter("btel", typeof(string));
    
            var bmobileParameter = bmobile != null ?
                new ObjectParameter("bmobile", bmobile) :
                new ObjectParameter("bmobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_BimehShodeh", bIDParameter, bFirstNameParameter, bFamilyParameter, bFatherParameter, bbirthCodeParameter, bbirthplcParameter, bbirthdateParameter, bregdateParameter, buserIdParameter, bbimecodeParameter, bJobParameter, bjobeCodeParameter, bbimehTypeParameter, bpersonelCodeParameter, btozihParameter, bramzParameter, bnatCodeParameter, bkargahNoParameter, btelParameter, bmobileParameter);
        }
    
        public virtual int Sp_insert_BimehShodeh1(string bFirstName, string bFamily, string bFather, string bbirthCode, string bbirthplc, string bbirthdate, string bregdate, Nullable<int> buserId, Nullable<int> bbimecode, string bJob, string bjobeCode, string bbimehType, Nullable<int> bpersonelCode, string btozih, string bramz, string bnatCode, Nullable<long> bkargahNo, string btel, string bmobile)
        {
            var bFirstNameParameter = bFirstName != null ?
                new ObjectParameter("bFirstName", bFirstName) :
                new ObjectParameter("bFirstName", typeof(string));
    
            var bFamilyParameter = bFamily != null ?
                new ObjectParameter("bFamily", bFamily) :
                new ObjectParameter("bFamily", typeof(string));
    
            var bFatherParameter = bFather != null ?
                new ObjectParameter("bFather", bFather) :
                new ObjectParameter("bFather", typeof(string));
    
            var bbirthCodeParameter = bbirthCode != null ?
                new ObjectParameter("bbirthCode", bbirthCode) :
                new ObjectParameter("bbirthCode", typeof(string));
    
            var bbirthplcParameter = bbirthplc != null ?
                new ObjectParameter("bbirthplc", bbirthplc) :
                new ObjectParameter("bbirthplc", typeof(string));
    
            var bbirthdateParameter = bbirthdate != null ?
                new ObjectParameter("bbirthdate", bbirthdate) :
                new ObjectParameter("bbirthdate", typeof(string));
    
            var bregdateParameter = bregdate != null ?
                new ObjectParameter("bregdate", bregdate) :
                new ObjectParameter("bregdate", typeof(string));
    
            var buserIdParameter = buserId.HasValue ?
                new ObjectParameter("buserId", buserId) :
                new ObjectParameter("buserId", typeof(int));
    
            var bbimecodeParameter = bbimecode.HasValue ?
                new ObjectParameter("bbimecode", bbimecode) :
                new ObjectParameter("bbimecode", typeof(int));
    
            var bJobParameter = bJob != null ?
                new ObjectParameter("bJob", bJob) :
                new ObjectParameter("bJob", typeof(string));
    
            var bjobeCodeParameter = bjobeCode != null ?
                new ObjectParameter("bjobeCode", bjobeCode) :
                new ObjectParameter("bjobeCode", typeof(string));
    
            var bbimehTypeParameter = bbimehType != null ?
                new ObjectParameter("bbimehType", bbimehType) :
                new ObjectParameter("bbimehType", typeof(string));
    
            var bpersonelCodeParameter = bpersonelCode.HasValue ?
                new ObjectParameter("bpersonelCode", bpersonelCode) :
                new ObjectParameter("bpersonelCode", typeof(int));
    
            var btozihParameter = btozih != null ?
                new ObjectParameter("btozih", btozih) :
                new ObjectParameter("btozih", typeof(string));
    
            var bramzParameter = bramz != null ?
                new ObjectParameter("bramz", bramz) :
                new ObjectParameter("bramz", typeof(string));
    
            var bnatCodeParameter = bnatCode != null ?
                new ObjectParameter("bnatCode", bnatCode) :
                new ObjectParameter("bnatCode", typeof(string));
    
            var bkargahNoParameter = bkargahNo.HasValue ?
                new ObjectParameter("bkargahNo", bkargahNo) :
                new ObjectParameter("bkargahNo", typeof(long));
    
            var btelParameter = btel != null ?
                new ObjectParameter("btel", btel) :
                new ObjectParameter("btel", typeof(string));
    
            var bmobileParameter = bmobile != null ?
                new ObjectParameter("bmobile", bmobile) :
                new ObjectParameter("bmobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_insert_BimehShodeh1", bFirstNameParameter, bFamilyParameter, bFatherParameter, bbirthCodeParameter, bbirthplcParameter, bbirthdateParameter, bregdateParameter, buserIdParameter, bbimecodeParameter, bJobParameter, bjobeCodeParameter, bbimehTypeParameter, bpersonelCodeParameter, btozihParameter, bramzParameter, bnatCodeParameter, bkargahNoParameter, btelParameter, bmobileParameter);
        }
    
        public virtual ObjectResult<SP_Show_AllUserInfo1_Result> SP_Show_AllUserInfo1(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Show_AllUserInfo1_Result>("SP_Show_AllUserInfo1", userIdParameter);
        }
    
        public virtual ObjectResult<SP_letterCount_Result> SP_letterCount(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_letterCount_Result>("SP_letterCount", userIDParameter);
        }
    
        public virtual int SP_UpdateMessage(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateMessage", userIDParameter);
        }
    
        public virtual int Sp_updateErjaMessage(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_updateErjaMessage", userIdParameter);
        }
    
        public virtual int Sp_DeleteUserAccess(Nullable<int> userID, Nullable<int> systemPartID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var systemPartIDParameter = systemPartID.HasValue ?
                new ObjectParameter("systemPartID", systemPartID) :
                new ObjectParameter("systemPartID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteUserAccess", userIDParameter, systemPartIDParameter);
        }
    
        public virtual ObjectResult<SP_Show_AllUserInfo2_Result> SP_Show_AllUserInfo2(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Show_AllUserInfo2_Result>("SP_Show_AllUserInfo2", userIdParameter);
        }
    }
}
