//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string Doc_subject { get; set; }
        public string Doc_description { get; set; }
        public string Doc_date { get; set; }
        public string Doc_exporter { get; set; }
        public string Doc_DeliveryFullname { get; set; }
        public Nullable<int> UserID { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileName { get; set; }
    
        public virtual User User { get; set; }
    }
}
