//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int newsid { get; set; }
        public string subject { get; set; }
        public string matn { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NewsDate { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentFileName { get; set; }
        public Nullable<int> AttachmentFileSize { get; set; }
    
        public virtual User User { get; set; }
    }
}
