//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class support
    {
        public int supportID { get; set; }
        public string support_subject { get; set; }
        public string support_description { get; set; }
        public int userId { get; set; }
        public string support_date { get; set; }
    
        public virtual User User { get; set; }
    }
}
