//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsereAccess
    {
        public int userAccessID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> SystemPardID { get; set; }
    
        public virtual systemPart systemPart { get; set; }
        public virtual User User { get; set; }
    }
}
