//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserLogId { get; set; }
        public string ComputerName { get; set; }
        public string IpAddress { get; set; }
        public string EnterDateTime { get; set; }
        public string ExitDateTime { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
