//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userjob
    {
        public int userJobsId { get; set; }
        public int userID { get; set; }
        public int JobId { get; set; }
        public string UserJobStartDate { get; set; }
        public string UserJobEndDate { get; set; }
        public byte Status { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
