//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BimehShodeh
    {
        public int bID { get; set; }
        public string bFirstName { get; set; }
        public string bFamily { get; set; }
        public string bFather { get; set; }
        public string bbirthCode { get; set; }
        public string bbirthplc { get; set; }
        public string bbirthdate { get; set; }
        public string bregdate { get; set; }
        public int buserId { get; set; }
        public int bbimecode { get; set; }
        public string bJob { get; set; }
        public string bjobeCode { get; set; }
        public string bbimehType { get; set; }
        public Nullable<int> bpersonelCode { get; set; }
        public string btozih { get; set; }
        public string bramz { get; set; }
        public string bnatCode { get; set; }
        public Nullable<long> bkargahNo { get; set; }
        public string farsiBimehType { get; set; }
        public int userID { get; set; }
        public string UserFullname { get; set; }
        public string btel { get; set; }
        public string bmobile { get; set; }
    }
}
