//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Letters
    {
        public int LetterId { get; set; }
        public string subject { get; set; }
        public string matn { get; set; }
        public string letterNo { get; set; }
        public string createDate { get; set; }
        public int userID { get; set; }
        public byte SecurityType { get; set; }
        public byte ForceType { get; set; }
        public byte BayganiType { get; set; }
        public byte PeygiryType { get; set; }
        public byte AttachmentType { get; set; }
        public byte LetterType { get; set; }
        public byte DraftType { get; set; }
        public string abstrct { get; set; }
        public byte answerType { get; set; }
        public string answerDeadline { get; set; }
        public string Reffrence { get; set; }
        public Nullable<int> replyLetterId { get; set; }
        public string FarsiSecurityType { get; set; }
        public string FarsiForceType { get; set; }
        public string FarsiBayganiType { get; set; }
        public string FarsiPeygiriType { get; set; }
        public string FarsiAttachmentType { get; set; }
        public string FarsiLetterType { get; set; }
        public string FarsiDraftType { get; set; }
        public string FarsiAnswerType { get; set; }
        public int Expr1 { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string Fullname { get; set; }
        public string sentLetterDate { get; set; }
    }
}
