//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Notes
    {
        public int noteID { get; set; }
        public string subject { get; set; }
        public string matn { get; set; }
        public string NoteDate { get; set; }
        public int userId { get; set; }
        public int Expr1 { get; set; }
        public string UserFamily { get; set; }
        public string UserFirstName { get; set; }
        public string FullNameCreator { get; set; }
    }
}
