//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_referenceLetter
    {
        public int LetterId { get; set; }
        public int UserID_sender { get; set; }
        public int UserID_Reciever { get; set; }
        public string ReferenceDate { get; set; }
        public Nullable<int> ReadType { get; set; }
        public string Description { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public int ReferenceLetterID { get; set; }
        public string farsiReadType { get; set; }
        public string Fullname_reciever { get; set; }
        public string fullname_sender { get; set; }
        public Nullable<byte> IsMessage { get; set; }
    }
}
