//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Remember
    {
        public int RememberID { get; set; }
        public string subject { get; set; }
        public string matn { get; set; }
        public string createDate { get; set; }
        public string DateRemember { get; set; }
        public byte IsRead { get; set; }
        public int UserId { get; set; }
        public string FarsiIsRead { get; set; }
    }
}
