//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_recieveNotes
    {
        public string subject { get; set; }
        public string matn { get; set; }
        public string NoteDate { get; set; }
        public int UserID_creator { get; set; }
        public string FullNameCreator { get; set; }
        public int sentNoteID { get; set; }
        public int NoteID { get; set; }
        public int UserID_girande { get; set; }
        public string FullName_reciever { get; set; }
    }
}
