//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SentNote
    {
        public int sentNoteID { get; set; }
        public int NoteID { get; set; }
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string FullName_reciever { get; set; }
    }
}
