//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_supports
    {
        public int supportID { get; set; }
        public string support_subject { get; set; }
        public string support_description { get; set; }
        public int userId { get; set; }
        public string support_date { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public int Expr4 { get; set; }
        public string Expr5 { get; set; }
        public int Expr6 { get; set; }
        public string Fullname { get; set; }
    }
}
