//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_UserJobs
    {
        public int userJobsId { get; set; }
        public int userID { get; set; }
        public int JobId { get; set; }
        public string UserJobStartDate { get; set; }
        public string UserJobEndDate { get; set; }
        public byte Status { get; set; }
        public string jobsName { get; set; }
        public Nullable<int> DetermineJobsLevel { get; set; }
        public string UserFirstName { get; set; }
        public string UserFamily { get; set; }
        public string FullName { get; set; }
        public string FarsiStatus { get; set; }
    }
}
