//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        public int worksID { get; set; }
        public string work_subject { get; set; }
        public string work_description { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> jobID { get; set; }
        public string dateDone { get; set; }
        public Nullable<int> timeDone { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
